2022-08-28 18:17:46,943 ERROR: Exception on /explore [GET] [in /Users/danielbianco/Documents/Flask/PA/microblog/venv/lib/python3.10/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/danielbianco/Documents/Flask/PA/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/danielbianco/Documents/Flask/PA/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/danielbianco/Documents/Flask/PA/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/danielbianco/Documents/Flask/PA/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/danielbianco/Documents/Flask/PA/microblog/venv/lib/python3.10/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/danielbianco/Documents/Flask/PA/microblog/app/routes.py", line 54, in explore
    return render_template('home.html', title='Home', lines=dates.items, next_url=next_url, prev_url=prev_url)
  File "/Users/danielbianco/Documents/Flask/PA/microblog/venv/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/Users/danielbianco/Documents/Flask/PA/microblog/venv/lib/python3.10/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Users/danielbianco/Documents/Flask/PA/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/Users/danielbianco/Documents/Flask/PA/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/danielbianco/Documents/Flask/PA/microblog/app/templates/home.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/danielbianco/Documents/Flask/PA/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/danielbianco/Documents/Flask/PA/microblog/venv/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/danielbianco/Documents/Flask/PA/microblog/venv/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/Users/danielbianco/Documents/Flask/PA/microblog/venv/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/Users/danielbianco/Documents/Flask/PA/microblog/venv/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block 'body'
    {% block content -%}
  File "/Users/danielbianco/Documents/Flask/PA/microblog/app/templates/base.html", line 48, in block 'content'
    {% block app_content %}{% endblock %}
  File "/Users/danielbianco/Documents/Flask/PA/microblog/app/templates/home.html", line 9, in block 'app_content'
    <a href="{{ url_for('reserve', period_id=line.id) }}">buchen</a>
  File "/Users/danielbianco/Documents/Flask/PA/microblog/venv/lib/python3.10/site-packages/flask/helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/danielbianco/Documents/Flask/PA/microblog/venv/lib/python3.10/site-packages/flask/helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "/Users/danielbianco/Documents/Flask/PA/microblog/venv/lib/python3.10/site-packages/werkzeug/routing.py", line 2315, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reserve' with values ['period_id']. Did you forget to specify values ['Period_id']?
2022-08-28 18:18:59,292 INFO: Microblog startup [in /Users/danielbianco/Documents/Flask/PA/microblog/app/__init__.py:47]
2022-08-28 18:19:05,175 ERROR: Exception on /explore [GET] [in /Users/danielbianco/Documents/Flask/PA/microblog/venv/lib/python3.10/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/danielbianco/Documents/Flask/PA/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/danielbianco/Documents/Flask/PA/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/danielbianco/Documents/Flask/PA/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/danielbianco/Documents/Flask/PA/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/danielbianco/Documents/Flask/PA/microblog/venv/lib/python3.10/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/danielbianco/Documents/Flask/PA/microblog/app/routes.py", line 54, in explore
    return render_template('home.html', title='Home', lines=dates.items, next_url=next_url, prev_url=prev_url)
  File "/Users/danielbianco/Documents/Flask/PA/microblog/venv/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/Users/danielbianco/Documents/Flask/PA/microblog/venv/lib/python3.10/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Users/danielbianco/Documents/Flask/PA/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/Users/danielbianco/Documents/Flask/PA/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/danielbianco/Documents/Flask/PA/microblog/app/templates/home.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/danielbianco/Documents/Flask/PA/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/danielbianco/Documents/Flask/PA/microblog/venv/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/danielbianco/Documents/Flask/PA/microblog/venv/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/Users/danielbianco/Documents/Flask/PA/microblog/venv/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/Users/danielbianco/Documents/Flask/PA/microblog/venv/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block 'body'
    {% block content -%}
  File "/Users/danielbianco/Documents/Flask/PA/microblog/app/templates/base.html", line 48, in block 'content'
    {% block app_content %}{% endblock %}
  File "/Users/danielbianco/Documents/Flask/PA/microblog/app/templates/home.html", line 9, in block 'app_content'
    <a href="{{ url_for('reserve', period_id=line.id) }}">buchen</a>
  File "/Users/danielbianco/Documents/Flask/PA/microblog/venv/lib/python3.10/site-packages/flask/helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/danielbianco/Documents/Flask/PA/microblog/venv/lib/python3.10/site-packages/flask/helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "/Users/danielbianco/Documents/Flask/PA/microblog/venv/lib/python3.10/site-packages/werkzeug/routing.py", line 2315, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reserve' with values ['period_id']. Did you forget to specify values ['Period_id']?
2022-08-28 22:58:03,818 INFO: Microblog startup [in /Users/danielbianco/Documents/Flask/PA/microblog/app/__init__.py:47]
